test_that("a design records its class, centre source and mixture", {
  d <- edetect_design(arl = 370, class = "bounded", center = 0.5, bounds = c(0, 1))
  expect_s3_class(d, "edetect_design")
  expect_equal(d$alpha, 1 / 370)
  expect_equal(d$center_source, "declared")
  expect_equal(sum(d$weights), 1)
  expect_true(all(d$lambda > 0))
  expect_true(all(d$delta > 0))
  expect_message(print(d), "bounded")
})

test_that("phase1 sets the centre and the scale and is recorded", {
  set.seed(1)
  x <- rnorm(50, 10, 2)
  d <- edetect_design(class = "subgaussian", phase1 = x)
  expect_equal(d$center, mean(x))
  expect_equal(d$sigma, sd(x))
  expect_equal(d$center_source, "phase1")
  expect_equal(d$n_phase1, 50L)
  dp <- edetect_design(class = "bernoulli", phase1 = data.frame(x = c(2, 3), n = c(100, 100)))
  expect_equal(dp$center, 0.025)
  expect_error(edetect_design(class = "bernoulli", phase1 = c(1, 2)), "data frame")
  expect_error(edetect_design(class = "subgaussian", center = 0), "sigma")
  expect_error(edetect_design(class = "bounded", center = 0.5), "bounds")
  expect_error(edetect_design(class = "bounded", bounds = c(0, 1)), "center")
})

test_that("directions mirror the bets and 'both' splits the weights", {
  up <- edetect_design(class = "bernoulli", center = 0.2, direction = "up")
  down <- edetect_design(class = "bernoulli", center = 0.2, direction = "down")
  both <- edetect_design(class = "bernoulli", center = 0.2, direction = "both")
  expect_true(all(up$lambda > 0)); expect_true(all(down$lambda < 0))
  expect_equal(length(both$lambda), length(up$lambda) + length(down$lambda))
  expect_equal(sum(both$weights[both$lambda > 0]), 0.5)
  expect_true(all(abs(down$delta) < 0.2))
})

test_that("user shifts and weights are honoured and validated", {
  d <- edetect_design(class = "subgaussian", center = 0, sigma = 2, delta = c(1, 4), weights = c(3, 1))
  expect_equal(d$lambda, c(1, 4) / 4)
  expect_equal(d$weights, c(0.75, 0.25))
  expect_error(edetect_design(class = "subgaussian", center = 0, sigma = 2, delta = -1), "positive")
  expect_error(edetect_design(class = "subgaussian", center = 0, sigma = 2, delta = 1, weights = c(1, 2)), "one weight per")
  expect_error(edetect_design(arl = 0.5, class = "subgaussian", center = 0, sigma = 1), "between")
  expect_error(edetect_design(class = "bounded", center = 1, bounds = c(0, 1), direction = "up"), "bound")
  expect_error(edetect_design(class = "poisson", center = 0, direction = "down"), "zero")
})
