test_that("the chart wrappers run end to end", {
  set.seed(2)
  cx <- edetect_x(runif(20, 0.3, 0.7), bounds = c(0, 1), center = 0.5, arl = 100)
  expect_s3_class(cx, "edetect_chart")
  expect_equal(cx$design$class, "bounded")
  cp <- edetect_p(x = c(1, 0, 2, 1), n = 100, center = 0.01, arl = 100)
  expect_equal(cp$design$class, "bernoulli")
  expect_equal(tidy(cp)$n, rep(100, 4))
  cc <- edetect_c(x = c(3, 2, 4), phase1 = c(3, 2, 4, 3, 2), arl = 100)
  expect_equal(cc$design$class, "poisson")
  expect_equal(cc$design$center, 2.8)
  cu <- edetect_u(x = c(3, 2, 4), n = c(2, 2, 3), center = 1.5, arl = 100)
  expect_equal(tidy(cu)$n, c(2, 2, 3))
  expect_s3_class(autoplot(cu), "ggplot")
})

test_that("the regression chart monitors Phase II residuals of a Phase I fit", {
  set.seed(3)
  d1 <- data.frame(z = 1:60); d1$y <- 2 + 0.5 * d1$z + rnorm(60, sd = 0.3)
  d2 <- data.frame(z = 61:120); d2$y <- 2 + 0.5 * d2$z + rnorm(60, sd = 0.3) + c(rep(0, 30), rep(1.5, 30))
  ch <- suppressWarnings(edetect_regression(y ~ z, phase1 = d1, phase2 = d2, arl = 200, direction = "up"))
  expect_s3_class(ch$fit, "lm")
  expect_equal(ch$design$center, 0)
  expect_equal(ch$design$center_source, "phase1")
  al <- edetect_alarm(ch)
  expect_true(al$alarm)
  expect_true(al$alarm_time > 30)
  expect_s3_class(autoplot(ch), "ggplot")
})

test_that("a chart with an alarm plots the alarm marks", {
  set.seed(4)
  ch <- suppressWarnings(edetect_x(c(runif(30, 0.3, 0.7), runif(30, 0.6, 1)), bounds = c(0, 1), center = 0.5, arl = 50))
  expect_true(edetect_alarm(ch)$alarm)
  p <- autoplot(ch)
  expect_s3_class(p, "ggplot")
  expect_error(autoplot(edetect_init(ch$design)), "no observations")
})
